name: credit
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - appdirs=1.4.4=pyhd3eb1b0_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - beautifulsoup4=4.13.5=py314hca03da5_0
  - bottleneck=1.4.2=py314hdbb4bc7_1
  - brotlicffi=1.1.0.0=py314h50f4ffc_0
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py314h73c2a22_1
  - charset-normalizer=3.4.4=py314hca03da5_0
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.14.0=py314hd8ed1ab_102
  - debugpy=1.8.17=py314hac9ea21_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fredapi=0.5.2=pyhd8ed1ab_0
  - frozendict=2.4.6=py314haa24f5a_0
  - html5lib=1.1=pyhd3eb1b0_0
  - icu=75.1=hfee45f7_0
  - idna=3.7=py314hca03da5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h237132a_0
  - libblas=3.9.0=39_h51639a9_openblas
  - libcblas=3.9.0=39_hb0561ab_openblas
  - libcxx=21.1.5=hf598326_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libiconv=1.18=h23cfdf5_2
  - liblapack=3.9.0=39_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libmpdec=4.0.0=h5505292_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.0=h8adb53f_0
  - libxgboost=3.1.1=cpu_h64a644d_0
  - libxml2=2.13.9=h4a9ca0c_0
  - libxslt=1.1.43=had6d056_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.5=h4a912ad_2
  - lxml=5.3.0=py314haa9d66a_1
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - multitasking=0.0.12=py314hca03da5_0
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.14.1=py314h4402d01_0
  - numpy=2.3.4=py314h5b5928d_0
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py314heb7d0cc_1
  - parso=0.8.5=pyhcf101f3_0
  - peewee=3.18.2=py314he09db74_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyh145f28c_0
  - platformdirs=4.5.0=py314hca03da5_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py314h9d33bd4_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-xgboost=3.1.1=cpu_pyh24504c9_0
  - pycparser=2.23=py314hca03da5_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=py314hca03da5_1
  - python=3.14.0=h40d2674_102_cp314
  - python-dateutil=2.9.0post0=py314hca03da5_2
  - python-gil=3.14.0=h4df99d1_102
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.14=8_cp314
  - pytz=2025.2=py314hca03da5_0
  - pyzmq=27.1.0=py312hd65ceae_0
  - readline=8.2=h1d1bf99_2
  - requests=2.32.5=py314hca03da5_1
  - scikit-learn=1.7.2=py314hcc665ce_0
  - scipy=1.16.3=py314h624bdf2_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=py314hca03da5_0
  - soupsieve=2.5=py314hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h892fb3f_3
  - tornado=6.5.2=py314h0612a62_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=py314hca03da5_0
  - typing_extensions=4.15.0=py314hca03da5_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=py314hca03da5_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webencodings=0.5.1=py314hca03da5_2
  - yfinance=0.2.57=pyhd8ed1ab_0
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zstd=1.5.7=h6491c7d_2
prefix: /opt/anaconda3/envs/credit
